//! Protobuf wire format: varints, tags, and length-delimited nesting.
//!
//! # Why this is hand-written and not generated
//!
//! `prost` would produce this from [`view.proto`](../../../proto/solstice/v1/view.proto),
//! and for most projects that is the right answer. Three things make it the
//! wrong one here.
//!
//! **It would need a second copy of every row.** Generated code gives its own
//! `Value`/`Row` structs, so encoding a view means building a parallel tree and
//! then serialising it. This encoder writes straight out of
//! [`solstice_ivm::Row`]. The whole point of measuring spike S1 is to find out
//! what a delta costs end to end; starting with an avoidable full copy on the
//! Rust side would measure the wrong thing.
//!
//! **It would put `protoc` in everyone's build.** `prost-build` shells out to it
//! from `build.rs`, so every contributor and every CI job needs it installed
//! before `cargo test` works — including the MSRV job, which exists to check a
//! compiler claim and has no business also checking a protobuf toolchain.
//!
//! **It would make the round trip self-referential.** prost encoding checked
//! against prost decoding proves the two agree, not that either matches the
//! spec. Here the `.proto` file stays normative and the oracles are *other
//! people's* implementations: the Dart and Kotlin decoders in `spikes/s1-decode`
//! are generated by `protoc` from that file and read these bytes. If this
//! encoder drifts from the spec, generated code in two other languages fails to
//! parse it — the same triple-oracle discipline the IVM crate already uses,
//! applied to the wire.
//!
//! # Length prefixes without a size pass
//!
//! A nested message needs its length before its body. The usual fix is a second
//! `encoded_len` traversal that mirrors the encoder, and mirrors are where bugs
//! live — the two drift and the result is a corrupt frame rather than a failed
//! compile.
//!
//! So instead the body is written first and the length varint is spliced in
//! afterwards ([`Encoder::message`]). That costs a `memmove` of the body per
//! nested message, which sounds worse than it is: the nesting here is four deep
//! and bounded by the schema, so the total moved is a small multiple of the
//! payload. One code path that cannot disagree with itself is worth more than
//! the memcpy.

/// Wire types. Only these three occur in the view schema: there are no fixed32
/// fields and no groups.
pub mod wire_type {
    pub const VARINT: u32 = 0;
    pub const I64: u32 = 1;
    pub const LEN: u32 = 2;
}

/// Largest varint: 64 bits at 7 bits per byte.
pub const MAX_VARINT: usize = 10;

/// Zigzag, for `sint64`.
///
/// Maps small negatives onto small positives so that `-1` costs one byte
/// instead of ten. The arithmetic shift is the point — `n >> 63` is all-ones
/// for negatives and all-zeros otherwise.
pub fn zigzag(n: i64) -> u64 {
    ((n << 1) ^ (n >> 63)) as u64
}

pub fn unzigzag(n: u64) -> i64 {
    ((n >> 1) as i64) ^ -((n & 1) as i64)
}

pub fn varint_into(mut v: u64, out: &mut [u8; MAX_VARINT]) -> usize {
    let mut n = 0;
    loop {
        let byte = (v & 0x7f) as u8;
        v >>= 7;
        if v == 0 {
            out[n] = byte;
            return n + 1;
        }
        out[n] = byte | 0x80;
        n += 1;
    }
}

#[derive(Debug, Default)]
pub struct Encoder {
    buf: Vec<u8>,
}

impl Encoder {
    pub fn new() -> Self {
        Encoder::default()
    }

    pub fn with_capacity(n: usize) -> Self {
        Encoder {
            buf: Vec::with_capacity(n),
        }
    }

    pub fn finish(self) -> Vec<u8> {
        self.buf
    }

    pub fn len(&self) -> usize {
        self.buf.len()
    }

    pub fn is_empty(&self) -> bool {
        self.buf.is_empty()
    }

    pub fn varint(&mut self, v: u64) {
        let mut tmp = [0u8; MAX_VARINT];
        let n = varint_into(v, &mut tmp);
        self.buf.extend_from_slice(&tmp[..n]);
    }

    pub fn tag(&mut self, field: u32, wire: u32) {
        self.varint(((field << 3) | wire) as u64);
    }

    pub fn uint32_field(&mut self, field: u32, v: u32) {
        // proto3 omits zero-valued scalars. Not merely an optimisation: the
        // decoder must default an absent field to zero anyway, so writing it
        // changes nothing a reader can observe, and index 0 is the single most
        // common index in a diff that prepends.
        if v != 0 {
            self.tag(field, wire_type::VARINT);
            self.varint(v as u64);
        }
    }

    pub fn uint64_field(&mut self, field: u32, v: u64) {
        if v != 0 {
            self.tag(field, wire_type::VARINT);
            self.varint(v);
        }
    }

    pub fn sint64_field(&mut self, field: u32, v: i64) {
        self.tag(field, wire_type::VARINT);
        self.varint(zigzag(v));
    }

    pub fn double_field(&mut self, field: u32, v: f64) {
        self.tag(field, wire_type::I64);
        self.buf.extend_from_slice(&v.to_bits().to_le_bytes());
    }

    /// Append bytes that are already in wire form.
    pub fn raw(&mut self, bytes: &[u8]) {
        self.buf.extend_from_slice(bytes);
    }

    pub fn bytes_field(&mut self, field: u32, v: &[u8]) {
        self.tag(field, wire_type::LEN);
        self.varint(v.len() as u64);
        self.buf.extend_from_slice(v);
    }

    /// A nested length-delimited message. `body` writes the contents; the
    /// length is spliced in once its size is known.
    pub fn message(&mut self, field: u32, body: impl FnOnce(&mut Self)) {
        self.tag(field, wire_type::LEN);
        let start = self.buf.len();
        body(self);
        let len = self.buf.len() - start;
        let mut tmp = [0u8; MAX_VARINT];
        let n = varint_into(len as u64, &mut tmp);
        self.buf.splice(start..start, tmp[..n].iter().copied());
    }
}

/// What a malformed frame can be.
///
/// Every variant here is reachable from bytes off a socket, so this is a parser
/// facing the internet at both ends of the cable (plan §6) and it returns
/// errors rather than panicking on any of them.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WireError {
    /// Ran off the end of the buffer mid-field.
    Truncated,
    /// A varint with no terminating byte inside ten bytes.
    VarintOverflow,
    /// A length prefix larger than the bytes that remain — the cheap way a
    /// hostile frame asks for a multi-gigabyte allocation.
    LengthOverrun { len: u64, remaining: usize },
    /// Wire type 3, 4 (groups, removed from proto3) or 6, 7 (never assigned).
    UnknownWireType(u32),
    /// Field number 0, which no tag may use.
    ZeroField,
    /// A field whose wire type is not the one its schema declares.
    TypeMismatch { field: u32, wire: u32 },
    /// Text that is not UTF-8.
    BadUtf8,
    /// Nesting past the depth the schema can produce. DQL caps relation
    /// traversal at depth 3 (plan §1.1); anything deeper is either a bug or a
    /// frame built to blow the stack.
    TooDeep,
}

impl std::fmt::Display for WireError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WireError::Truncated => write!(f, "truncated frame"),
            WireError::VarintOverflow => write!(f, "varint longer than 10 bytes"),
            WireError::LengthOverrun { len, remaining } => {
                write!(f, "length prefix {len} with only {remaining} bytes left")
            }
            WireError::UnknownWireType(w) => write!(f, "unknown wire type {w}"),
            WireError::ZeroField => write!(f, "field number 0"),
            WireError::TypeMismatch { field, wire } => {
                write!(f, "field {field} has wire type {wire}, which it never uses")
            }
            WireError::BadUtf8 => write!(f, "text field is not valid UTF-8"),
            WireError::TooDeep => write!(f, "nested past the maximum depth"),
        }
    }
}

impl std::error::Error for WireError {}

/// Deeper than any view the query language can describe: three levels of
/// relation traversal, each adding a `RowList`/`Row`/`Value` layer, plus the
/// `ViewDelta`/`ViewChange`/`Added` frame on top.
pub const MAX_DEPTH: u32 = 24;

pub struct Decoder<'a> {
    buf: &'a [u8],
    pos: usize,
    depth: u32,
}

/// A tag, split into its parts.
pub struct Tag {
    pub field: u32,
    pub wire: u32,
}

impl<'a> Decoder<'a> {
    pub fn new(buf: &'a [u8]) -> Self {
        Decoder {
            buf,
            pos: 0,
            depth: 0,
        }
    }

    pub fn is_done(&self) -> bool {
        self.pos >= self.buf.len()
    }

    pub fn varint(&mut self) -> Result<u64, WireError> {
        let mut result = 0u64;
        for shift in 0..MAX_VARINT {
            let byte = *self.buf.get(self.pos).ok_or(WireError::Truncated)?;
            self.pos += 1;
            // The tenth byte carries a single bit; protobuf accepts any value
            // there and truncates, matching every other implementation.
            result |= ((byte & 0x7f) as u64).wrapping_shl(shift as u32 * 7);
            if byte & 0x80 == 0 {
                return Ok(result);
            }
        }
        Err(WireError::VarintOverflow)
    }

    pub fn tag(&mut self) -> Result<Tag, WireError> {
        let key = self.varint()?;
        let field = (key >> 3) as u32;
        let wire = (key & 7) as u32;
        if field == 0 {
            return Err(WireError::ZeroField);
        }
        Ok(Tag { field, wire })
    }

    pub fn fixed64(&mut self) -> Result<u64, WireError> {
        let end = self.pos.checked_add(8).ok_or(WireError::Truncated)?;
        let slice = self.buf.get(self.pos..end).ok_or(WireError::Truncated)?;
        self.pos = end;
        let mut bytes = [0u8; 8];
        bytes.copy_from_slice(slice);
        Ok(u64::from_le_bytes(bytes))
    }

    pub fn bytes(&mut self) -> Result<&'a [u8], WireError> {
        let len = self.varint()?;
        let remaining = self.buf.len() - self.pos;
        // Checked before any allocation, so a frame claiming four gigabytes
        // costs an error rather than four gigabytes.
        if len > remaining as u64 {
            return Err(WireError::LengthOverrun { len, remaining });
        }
        let start = self.pos;
        self.pos += len as usize;
        Ok(&self.buf[start..self.pos])
    }

    pub fn string(&mut self) -> Result<&'a str, WireError> {
        std::str::from_utf8(self.bytes()?).map_err(|_| WireError::BadUtf8)
    }

    /// Read a nested message by handing its bytes to `body` as a fresh decoder
    /// that cannot see past them.
    pub fn message<T>(
        &mut self,
        body: impl FnOnce(&mut Decoder<'a>) -> Result<T, WireError>,
    ) -> Result<T, WireError> {
        if self.depth >= MAX_DEPTH {
            return Err(WireError::TooDeep);
        }
        let inner_buf = self.bytes()?;
        let mut inner = Decoder {
            buf: inner_buf,
            pos: 0,
            depth: self.depth + 1,
        };
        let out = body(&mut inner)?;
        Ok(out)
    }

    /// Skip a field this decoder does not know.
    ///
    /// Required, not optional politeness: plan §3.5 promises that field numbers
    /// are never reused and that an old client meets a newer server. Skipping is
    /// how that promise is kept, and a decoder that errors on an unknown field
    /// turns every additive schema change into a breaking one.
    pub fn skip(&mut self, wire: u32) -> Result<(), WireError> {
        match wire {
            wire_type::VARINT => {
                self.varint()?;
            }
            wire_type::I64 => {
                self.fixed64()?;
            }
            wire_type::LEN => {
                self.bytes()?;
            }
            // 5 is fixed32; nothing in this schema emits it, but a future field
            // might, so it is skippable rather than an error.
            5 => {
                let end = self.pos.checked_add(4).ok_or(WireError::Truncated)?;
                if end > self.buf.len() {
                    return Err(WireError::Truncated);
                }
                self.pos = end;
            }
            other => return Err(WireError::UnknownWireType(other)),
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn varints_round_trip_at_the_boundaries() {
        for v in [0, 1, 127, 128, 16383, 16384, u32::MAX as u64, u64::MAX] {
            let mut e = Encoder::new();
            e.varint(v);
            let buf = e.finish();
            assert_eq!(Decoder::new(&buf).varint(), Ok(v), "value {v}");
        }
    }

    #[test]
    fn zigzag_keeps_small_negatives_small() {
        // The reason `sint64` is in the schema at all: without it, every
        // negative integer in every row costs the full ten bytes.
        for v in [0i64, -1, 1, -2, 2, i64::MIN, i64::MAX] {
            assert_eq!(unzigzag(zigzag(v)), v);
        }
        let mut tmp = [0u8; MAX_VARINT];
        assert_eq!(varint_into(zigzag(-1), &mut tmp), 1);
        assert_eq!(varint_into(zigzag(i64::MIN), &mut tmp), 10);
    }

    #[test]
    fn a_length_prefix_cannot_ask_for_memory_that_is_not_there() {
        // A hostile frame's cheapest attack: five bytes claiming a gigabyte.
        let buf = [0xff, 0xff, 0xff, 0xff, 0x0f];
        assert!(matches!(
            Decoder::new(&buf).bytes(),
            Err(WireError::LengthOverrun { .. })
        ));
    }

    #[test]
    fn nesting_is_written_once_and_measured_afterwards() {
        // The splice trick: the inner body lands first, the length goes in
        // front of it, and the outer message's own length counts the lot.
        let mut e = Encoder::new();
        e.message(1, |e| {
            e.message(1, |e| e.bytes_field(1, b"deep"));
        });
        let buf = e.finish();

        let mut d = Decoder::new(&buf);
        let t = d.tag().unwrap();
        assert_eq!((t.field, t.wire), (1, wire_type::LEN));
        let inner = d
            .message(|d| {
                d.tag()?;
                d.message(|d| {
                    d.tag()?;
                    d.bytes()
                })
            })
            .unwrap();
        assert_eq!(inner, b"deep");
    }

    #[test]
    fn a_nested_decoder_cannot_read_past_its_own_message() {
        // Containment is what makes `skip` safe: an inner message that lies
        // about its contents still cannot consume the next field of its parent.
        let mut e = Encoder::new();
        e.message(1, |e| e.uint32_field(1, 7));
        e.uint32_field(2, 9);
        let buf = e.finish();

        let mut d = Decoder::new(&buf);
        d.tag().unwrap();
        d.message(|inner| {
            inner.tag()?;
            inner.varint()?;
            assert!(inner.is_done());
            Ok(())
        })
        .unwrap();
        let t = d.tag().unwrap();
        assert_eq!(t.field, 2);
        assert_eq!(d.varint(), Ok(9));
        assert!(d.is_done());
    }

    #[test]
    fn unknown_fields_are_skipped_and_not_rejected() {
        // Plan §3.5: an old client meets a newer server and keeps working.
        let mut e = Encoder::new();
        e.uint32_field(99, 1);
        e.double_field(98, 1.0);
        e.bytes_field(97, b"future");
        e.uint32_field(1, 42);
        let buf = e.finish();

        let mut d = Decoder::new(&buf);
        let mut found = None;
        while !d.is_done() {
            let t = d.tag().unwrap();
            if t.field == 1 {
                found = Some(d.varint().unwrap());
            } else {
                d.skip(t.wire).unwrap();
            }
        }
        assert_eq!(found, Some(42));
    }

    #[test]
    fn a_truncated_frame_is_an_error_and_never_a_panic() {
        let mut e = Encoder::new();
        e.message(1, |e| e.bytes_field(1, b"hello world"));
        let full = e.finish();
        for cut in 1..full.len() {
            let mut d = Decoder::new(&full[..cut]);
            // Whatever it does, it returns.
            let _ = d
                .tag()
                .and_then(|_| d.message(|i| i.bytes().map(|b| b.len())));
        }
    }

    #[test]
    fn proto3_leaves_out_zero_valued_scalars() {
        let mut e = Encoder::new();
        e.uint32_field(1, 0);
        e.uint64_field(2, 0);
        assert!(e.is_empty());
    }
}
